# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=200)),
                ('result', models.IntegerField(default=-1)),
                ('insertdata', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
